version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
  nextjs:
    build:
      context: ./
    ports:
      - "3000:3000"
    container_name: next-app
    stdin_open: true
    volumes:
       - .:/src
       - /src/node_modules
volumes:
  postgres-db:
  redis: